export const APP_TIME_ZONE = process.env.APP_TIME_ZONE || "America/Bogota";

// All persisted timestamps are UTC Date values generated by the server. The
// timezone is only used when presenting a date/time to people.
export const getServerTime = () => {
  const now = new Date();
  return {
    now: now.toISOString(),
    timeZone: APP_TIME_ZONE,
    display: new Intl.DateTimeFormat("es-CO", {
      timeZone: APP_TIME_ZONE,
      dateStyle: "full",
      timeStyle: "medium",
    }).format(now),
  };
};
